// Code generated by protoc-gen-go.
// source: config.proto
// DO NOT EDIT!

/*
Package pbft is a generated protocol buffer package.

It is generated from these files:
	config.proto
	messages.proto

It has these top-level messages:
	PbftConfig
	BatchConfig
	Message
	Request
	PrePrepare
	Prepare
	Commit
	BlockInfo
	Checkpoint
	ViewChange
	PQset
	NewView
	FetchRequest
	RequestBlock
	BatchMessage
	Metadata
*/
package pbft

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type PbftConfig struct {
	N                       uint64 `protobuf:"varint,1,opt,name=n" json:"n,omitempty"`
	F                       uint64 `protobuf:"varint,2,opt,name=f" json:"f,omitempty"`
	K                       uint64 `protobuf:"varint,3,opt,name=k" json:"k,omitempty"`
	LMultiplier             uint64 `protobuf:"varint,4,opt,name=l_multiplier" json:"l_multiplier,omitempty"`
	ViewchangePeriod        uint64 `protobuf:"varint,5,opt,name=viewchange_period" json:"viewchange_period,omitempty"`
	RequestTimeout          uint64 `protobuf:"varint,6,opt,name=request_timeout" json:"request_timeout,omitempty"`
	ViewchangeResendTimeout uint64 `protobuf:"varint,7,opt,name=viewchange_resend_timeout" json:"viewchange_resend_timeout,omitempty"`
	ViewchangeTimeout       uint64 `protobuf:"varint,8,opt,name=viewchange_timeout" json:"viewchange_timeout,omitempty"`
	NullRequestTimeout      uint64 `protobuf:"varint,9,opt,name=null_request_timeout" json:"null_request_timeout,omitempty"`
}

func (m *PbftConfig) Reset()         { *m = PbftConfig{} }
func (m *PbftConfig) String() string { return proto.CompactTextString(m) }
func (*PbftConfig) ProtoMessage()    {}

type BatchConfig struct {
	PbftConfig   *PbftConfig `protobuf:"bytes,1,opt,name=pbft_config" json:"pbft_config,omitempty"`
	BatchSize    uint64      `protobuf:"varint,2,opt,name=batch_size" json:"batch_size,omitempty"`
	BatchTimeout uint64      `protobuf:"varint,3,opt,name=batch_timeout" json:"batch_timeout,omitempty"`
	Outstanding  uint64      `protobuf:"varint,4,opt,name=outstanding" json:"outstanding,omitempty"`
}

func (m *BatchConfig) Reset()         { *m = BatchConfig{} }
func (m *BatchConfig) String() string { return proto.CompactTextString(m) }
func (*BatchConfig) ProtoMessage()    {}

func (m *BatchConfig) GetPbftConfig() *PbftConfig {
	if m != nil {
		return m.PbftConfig
	}
	return nil
}
